baseURL = "https://sirosabzi.com/"
locale = "en"
title = "SIR و SABZI"
paginate = 10
enableRobotsTXT = true
enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.imports]]
    path = "github.com/jpanther/congo/v2"

[outputs]
  home     = ["HTML", "RSS", "JSON"]
  page     = ["HTML"]
  section  = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term     = ["HTML"]
