[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "pages/about"
  weight = 20

[[main]]
  name = "Support"
  pageRef = "pages/support"
  weight = 30

[[main]]
  identifier = "search"
  weight = 40
  [main.params]
    action = "search"
