[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  url = "/pages/about/"
  weight = 20

[[main]]
  name = "Support"
  url = "/pages/support/"
  weight = 30

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[footer]]
  name = "RSS"
  url = "/index.xml"
  weight = 10

[[footer]]
  name = "Support"
  url = "/pages/support/"
  weight = 20
