colorScheme = "fire"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = false
mainSections = ["posts"]
description = "A food blog celebrating Persian and international cuisine"

[author]
  name = "Amir"

[homepage]
  layout = "page"
  showRecent = true
  recentLimit = 10
  showMoreLink = false
  showMoreLinkDest = "/posts/"
  cardView = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showAuthor = false
  showHero = true
  heroStyle = "big"
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  showReadingTime = true
  showTableOfContents = false
  showRelatedContent = false
  showWordCount = false
  showPagination = true

[list]
  showBreadcrumbs = false
  showTableOfContents = false
  showSummary = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[search]
  enabled = true
  type = "fuse"
  fuzzy = false
  minMatchCharLength = 2
  includeResults = false

[analytics]
  [analytics.google]
    id = "G-2CEB9PTEG2"
